### ISSUE TITLE
Add array for rockets, so we can fire 2+ rockets at once

### ISSUE THREAD

**Issue by DarthVanger** [DarthVanger/ghost-of-kyiv#119]
## Task
Right now player can not fire 2nd rocket, before the 1st one reached the end of the screen.

We want to allow to fire multiple rockets, so we need array of rockets.

## Todo
- [ ] Create `rockets = []` empty array in `rovket.js`
- [ ] When we press `r` key, we should create a new `rocket`, and push it into the `rockets` array.
- [ ] In `step.js` move each `rocket` each FPS: `rockets.forEach(moveRocket)`
- [ ] In `step.js` render each `rocket` each FPS: `rockets.forEach(renderRocket)`
- [ ] In `step.js` each FPS check if `rocket` reached end of screen.
  - [ ] If rocket reached end of screen, remove it from the array, and remove rocket image from HTML.
